#version 100 
uniform highp vec4 u_world[4];
uniform highp vec3 u_lightDir;
uniform highp vec4 u_projection[4];
uniform highp vec4 u_viewInverse[4];
uniform highp vec4 u_view[4];
attribute highp vec4 a_position;
attribute highp vec2 a_texCoord;
attribute highp vec3 a_normal;
attribute highp vec4 a_tangent;
varying highp vec2 var_TEXCOORD0;
varying highp vec3 var_TEXCOORD1;
varying highp vec3 var_TEXCOORD2;
varying highp vec3 var_TEXCOORD3;
void main()
{
	highp vec3 v0;
	highp vec4 v1;
	v1.x = dot(u_world[0],a_position);
	v1.y = dot(u_world[1],a_position);
	v1.z = dot(u_world[2],a_position);
	v1.w = dot(u_world[3],a_position);
	highp vec4 v2;
	v2.x = dot(u_view[0],v1);
	v2.y = dot(u_view[1],v1);
	v2.z = dot(u_view[2],v1);
	v2.w = dot(u_view[3],v1);
	highp vec4 v3;
	v3.x = dot(u_projection[0],v2);
	v3.y = dot(u_projection[1],v2);
	v3.z = dot(u_projection[2],v2);
	v3.w = dot(u_projection[3],v2);
	highp vec3 v4;
	v4.x = dot(u_world[0].xyz,a_normal);
	v4.y = dot(u_world[1].xyz,a_normal);
	v4.z = dot(u_world[2].xyz,a_normal);
	highp vec3 v5;
	v5.xyz = normalize(v4);
	highp vec3 v6;
	v6.x = dot(u_world[0].xyz,a_tangent.xyz);
	v6.y = dot(u_world[1].xyz,a_tangent.xyz);
	v6.z = dot(u_world[2].xyz,a_tangent.xyz);
	highp vec3 v7;
	v7.xyz = normalize(v6);
	highp vec3 v8;
	v8.xyz = (cross(v7,v5)*a_tangent.www);
	highp vec3 v9;
	v9.x = u_viewInverse[0].w;
	v9.y = u_viewInverse[1].w;
	v9.z = u_viewInverse[2].w;
	highp vec3 v10;
	v10.xyz = normalize((v9+(-v1.xyz)));
	highp vec3 v11;
	v11.x = dot(v7,u_lightDir);
	v11.y = dot(v8,u_lightDir);
	v11.z = dot(v5,u_lightDir);
	highp vec3 v12;
	v12.x = dot(v7,v10);
	v12.y = dot(v8,v10);
	v12.z = dot(v5,v10);
	gl_Position.xyzw = v3;
	var_TEXCOORD0.xy = a_texCoord;
	var_TEXCOORD1.xyz = v11;
	var_TEXCOORD2.xyz = v12;
	var_TEXCOORD3.xyz = v0;
}

